apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gocd-crb
  labels:
    app: "gocd"
subjects:
- kind: ServiceAccount
  name: gocd-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gocd-cr
